# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

schedules:
  - cron: "*/35 * * * *"
    displayName: Monthly Build
    branches:
      include:
      - master
    always: true

pool:
  vmImage: windows-latest


stages:
- stage: Compile
  jobs:
  - job: Compile_Jobs
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true

